"""
Django settings for project_QuickFix project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rsioxt(j*vq71tjp9jx^u(j4(4*^n=g)4!cr!886)mj6=+sss9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Pagamento via PIX (MVP)
# -------------------------------------------------
PIX_KEY = "seu-email-ou-chave-aleatoria@pix.com.br"   # chave Pix (e-mail, aleatória, tel, CPF/CNPJ)
PIX_MERCHANT_NAME = "QUICKFIX LTDA"                   # máx. 25 chars (sem acento)
PIX_MERCHANT_CITY = "CAMPINAS"                        # sem acento, máx. 15 chars

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_browser_reload',        # ⚠️ Opcional, só se usar Django-Browser-Reload
    'django.contrib.admin',         # ✅ ESSENCIAL
    'django.contrib.messages',      # ✅ ESSENCIAL
    'django.contrib.staticfiles',   # ✅ ESSENCIAL
    'django.contrib.auth',          # ✅ ESSENCIAL: fornece User model, login, logout
    'django.contrib.contenttypes',  # ✅ ESSENCIAL: mapeia seus modelos para uso interno
    'django.contrib.sessions',      # ✅ ESSENCIAL: armazena sessões (como login)
    'widget_tweaks',                # ✅ Para estilizar os widgets do Django (ex: campos de formulário)
    'app_QuickFix',
    'django_filters',# ✅ Para filtros avançados
]

MIDDLEWARE = [
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_QuickFix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_QuickFix.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'quickfix',
        'USER': 'root',
        'PASSWORD': '1234',
        'HOST': 'localhost',  # mesmo nome do serviço Docker no docker-compose
        'PORT': '3306',     # porta interna do container
    }
}

# Password validationd
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/dd


#! ??????
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field typeS
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'app_QuickFix.CustomUser'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'desesperoprojetodespair@gmail.com'  # <-- coloque seu email aqui
EMAIL_HOST_PASSWORD = 'ijqy qtcs kmsk huot'  # <-- coloque a senha gerada lá
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'

# Redirecionamento após login e logoSut
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/' # Para onde ir após o login bem-sucedido
LOGOUT_REDIRECT_URL = '/' # Para onde ir após o logout
