# Generated by Django 5.2 on 2025-05-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_QuickFix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
