# Generated by Django 5.2 on 2025-09-25 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_QuickFix', '0003_directthread_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directthread',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directthread',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_as_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
