# Generated by Django 5.2 on 2025-10-08 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_QuickFix', '0004_alter_directthread_user1_alter_directthread_user2'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico_contratado',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='servico_contratado',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='servico_contratado',
            name='txid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=35),
        ),
        migrations.AddField(
            model_name='servico_contratado',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='titulo',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='servico_visualizacao',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='app_QuickFix.servico'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['status', 'data_criacao'], name='Servicos_status_3f3019_idx'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['titulo'], name='Servicos_titulo_0f2957_idx'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['preco'], name='Servicos_preco_f33b34_idx'),
        ),
        migrations.AddIndex(
            model_name='servico_avaliacao',
            index=models.Index(fields=['data_criacao'], name='Servico_ava_data_cr_c07207_idx'),
        ),
        migrations.AddIndex(
            model_name='servico_contratado',
            index=models.Index(fields=['status', 'data_criacao'], name='Servico_con_status_dda7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='servico_favoritos',
            index=models.Index(fields=['data_criacao'], name='Servico_fav_data_cr_62e484_idx'),
        ),
        migrations.AddIndex(
            model_name='servico_visualizacao',
            index=models.Index(fields=['data_criacao'], name='Servico_vis_data_cr_d1711d_idx'),
        ),
        migrations.AddConstraint(
            model_name='servico_favoritos',
            constraint=models.UniqueConstraint(fields=('user', 'servico'), name='uniq_fav_user_servico'),
        ),
    ]
