# Generated by Django 5.2 on 2025-11-08 17:24

from django.db import migrations
import uuid

def fill_missing_emails(apps, schema_editor):
    User = apps.get_model('app_QuickFix', 'CustomUser')
    # Garanta unicidade gerando um endereço sintético por usuário
    for u in User.objects.filter(email__isnull=True):
        base = (u.username or 'user').lower()
        # acrescenta um sufixo para garantir unicidade mesmo se repetir username
        u.email = f"{base}-{uuid.uuid4().hex[:8]}@quickfix.local"
        u.save(update_fields=['email'])

class Migration(migrations.Migration):

    dependencies = [
        ('app_QuickFix', '0007_fill_emails'),
    ]

    operations = [
         migrations.RunPython(fill_missing_emails, migrations.RunPython.noop),
    ]
