# Generated by Django 5.2 on 2025-11-08 17:31

from django.db import migrations

def fill_missing_emails(apps, schema_editor):
    User = apps.get_model('app_QuickFix', 'CustomUser')
    # Preenche emails nulos com algo único baseado no username
    for u in User.objects.filter(email__isnull=True):
        base = f"{u.username.lower()}@local.invalid"
        email = base
        i = 1
        # garante unicidade mesmo se houver duplicados de username
        while User.objects.filter(email=email).exclude(pk=u.pk).exists():
            i += 1
            email = f"{u.username.lower()}+{i}@local.invalid"
        u.email = email
        u.save(update_fields=['email'])

class Migration(migrations.Migration):

    dependencies = [
        ('app_QuickFix', '0008_fill_emails'),
    ]

    operations = [
         migrations.RunPython(fill_missing_emails, migrations.RunPython.noop)
    ]
