# Generated by Django 5.2 on 2025-11-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_QuickFix', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico_contratado',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
